import { run, claudeCode, Output } from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

// Drains a spec's agent-ready tickets to a reviewed draft PR.
//
//   plan → implement one ticket → re-plan → … → compose PR → review
//
// Every phase is a fresh container, so no context carries between tickets, and
// re-planning after each one means every dispatch sees live tracker state.
//
// Agents own the tracker mutations, where the quirks live. This script owns the
// verdicts: what is workable, whether blockers are clear, whether the claimed
// work happened, which branch it happened on, plus limits and sequencing.

// Per-repo tuning, before anything reads it. Credentials are not environment
// at all; see resolveCredentials().
loadConfig();

// Per phase, so the expensive model goes where judgment is worth paying for.
// TO_DONE_MODEL sets every phase; TO_DONE_MODEL_<PHASE> overrides one.
const model = (phase: string, fallback: string): string =>
  process.env[`TO_DONE_MODEL_${phase}`]?.trim() || process.env.TO_DONE_MODEL?.trim() || fallback;

const MODELS = {
  planner: model("PLANNER", "claude-sonnet-5"),
  implementer: model("IMPLEMENTER", "claude-opus-5"),
  prComposer: model("PR_COMPOSER", "claude-sonnet-5"),
  prReviewer: model("PR_REVIEWER", "claude-opus-5"),
};

const COMPLETION_SIGNAL = "<promise>COMPLETE</promise>";

// Lets the driver find the reviewer's verdict comment without reading it.
const REVIEW_MARKER = "<!-- to-done:reviewed -->";

const LIMITS = {
  outerIter: 50, // tickets, not planning rounds
  wallTimeMs: 6 * 60 * 60 * 1000,
  ticketTries: 3, // the third dispatch forces a bail-out
  consecutiveFailures: 4, // circuit breaker; any closed ticket resets it
  transientRetries: 3, // per phase, on top of the ticket-level retry
  retryBaseMs: 30_000, // doubles each attempt
  plannerMaxIter: 1,
  implementerMaxIter: 1,
  prComposerMaxIter: 1,
  reviewerMaxIter: 1,
  implementerIdleSeconds: 1200,
};

// Substituted into every prompt, so the rule and the signal have one home.
const DISCIPLINE = `The Procedure is a single multi-step transaction. From any intermediate step, continue to the next, and do not stop. The only valid termination is a step that emits ${COMPLETION_SIGNAL}.`;
const DISCLAIMER = "_Generated by an AI agent._";

const SKILL_DIR = path.resolve(fileURLToPath(import.meta.url), "../..");
const promptPath = (name: string): string => path.join(SKILL_DIR, name);

// Up here because resolveLabels() is called at module scope below, declared
// beside that function, it would still be in its temporal dead zone.
const TRIAGE_DOC = "docs/agents/triage-labels.md";
const SECRETS_FILE = path.resolve(".to-done", "secrets");

/** Terminal for this run: stop dispatching, file a partial PR, exit 1. */
class IncompleteError extends Error {}

type Ticket = { number: number; title: string; body: string };
type Excluded = { number: number; reason: string };

/**
 * Bodies are carried for the planner's prompt, which ranks from them. Every
 * other consumer wants the identity, and a body in a human-read report or a
 * second agent's prompt is noise it has to skip past.
 */
const titlesOnly = (tickets: Ticket[]) => tickets.map(({ number, title }) => ({ number, title }));

/** What the driver knows about the queue, recomputed before every dispatch. */
type Frontier = {
  /** Open, agent-ready, and verified to have no open blockers. */
  workable: Ticket[];
  /** Open and agent-ready, blocked or not. A superset of `workable`. */
  remaining: Ticket[];
  /** Agent-ready but not dispatchable, each with the reason it was skipped. */
  excluded: Excluded[];
};

const EMPTY_FRONTIER: Frontier = { workable: [], remaining: [], excluded: [] };

const sh = (command: string): string =>
  execSync(command, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();

const git = (args: string): string => sh(`git ${args}`);

/**
 * Everything the error actually says. `execSync` sets `message` to
 * "Command failed: <cmd>" and puts the process's own stderr in `stderr`, so
 * reading the first line alone reports every git and gh failure as the command
 * that failed with no reason attached.
 */
const message = (e: unknown): string => {
  if (!(e instanceof Error)) return String(e).trim();
  const stderr = (e as { stderr?: unknown }).stderr?.toString().trim();
  return (stderr ? `${e.message.split("\n")[0]}\n${stderr}` : e.message).trim();
};

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

const fail = (reason: string): never => {
  console.error(reason);
  process.exit(2);
};

const USAGE = "Usage: loop.mts <slug> [auto | plan | implement <ticket> | pr | review] [--force]";

// ---------------------------------------------------------------------------
// Launch configuration
// ---------------------------------------------------------------------------

const { slug, phase, phaseArg, force } = parseArgs(process.argv.slice(2));

// Repo-relative, because most reads go through a git ref rather than the disk.
const SCRATCH_DIR = `.scratch/${slug}`;
const SCRATCH_ISSUES = `${SCRATCH_DIR}/issues`;
const TRACKER = existsSync(path.resolve(SCRATCH_ISSUES)) ? "local" : "github";
const BRANCH = `agent/${slug}`;
const SPEC_LABEL = `spec:${slug}`;

// One image per repo; build-image.sh derives the same name from the same repo.
const IMAGE_NAME = process.env.TO_DONE_IMAGE?.trim() || `to-done:${repoTag()}`;

const LABELS = resolveLabels();
const { env: sandboxEnv, using: authUsing } = resolveCredentials();

// Under `.to-done/`, not `.sandcastle/`: these are what you read when a run
// goes wrong, so they belong under this tool's name.
const LOG_DIR = path.resolve(
  ".to-done/logs",
  `${slug}-${new Date().toISOString().replace(/[:.]/g, "-")}`,
);
console.error(`Tracker: ${TRACKER}  Branch: ${BRANCH}  Logs: ${LOG_DIR}`);
console.error(
  `Models: ${Object.entries(MODELS)
    .map(([p, m]) => `${p}=${m}`)
    .join("  ")}`,
);
console.error(`Auth: ${authUsing.join("  ")}`);
// Reported, not held: every phase re-reads the live credential when its own
// container launches, so nothing resolved here is what any of them will use.
reportCodexCredential();

// After the config trail, so a missing image still shows what would have run.
requireImage();
requireQueue();
mkdirSync(LOG_DIR, { recursive: true });

/**
 * Built per phase launch, not once per run. The codex credential is a live file
 * with an expiry, and a drain runs for hours, so one provider made at startup
 * would hand the last phase a credential read before the first ticket began.
 * Sandcastle bakes env per sandbox rather than per run, so a fresh provider is
 * what a fresh read means.
 */
const phaseSandbox = (codex = resolveCodexCredential()) =>
  docker({
    imageName: IMAGE_NAME,
    env: { CI: "true", ...sandboxEnv, ...codex.env },
  });

/**
 * Shared run config for every phase. `branch` is the branch the phase is
 * checked out on, always set, because an unset strategy defaults a bind-mount
 * sandbox to the host checkout, which would run the phase in the user's own
 * working tree. `deps` is whether the phase needs a working dependency tree; it
 * gates the copied `node_modules` and the repo's install command together,
 * since the install has nothing to install without the copy.
 */
const phaseOpts = ({ branch, base, deps }: { branch: string; base?: string; deps: boolean }) => ({
  branchStrategy: {
    type: "branch" as const,
    branch,
    ...(base ? { baseBranch: base } : {}),
  },
  copyToWorktree: deps && existsSync(path.resolve("node_modules")) ? ["node_modules"] : [],
  hooks: {
    sandbox: {
      onSandboxReady: [
        // Rewrite git's remotes to HTTPS + GH_TOKEN so pushes need no SSH key.
        { command: "gh auth setup-git" },
        { command: codexLoginCommand() },
        ...(deps && process.env.TO_DONE_SETUP
          ? [{ command: process.env.TO_DONE_SETUP, timeoutMs: 600_000 }]
          : []),
      ],
    },
  },
  timeouts: {
    copyToWorktreeMs: 120_000,
    gitSetupMs: 30_000,
    commitCollectionMs: 60_000,
    mergeToHostMs: 60_000,
  },
});

const logging = (name: string) =>
  ({ type: "file", path: path.join(LOG_DIR, `${name}.log`) }) as const;

// ---------------------------------------------------------------------------
// Failure classes, failing closed at ticket scope: only a systemic fault ends
// the run, everything else costs one ticket at most.
// ---------------------------------------------------------------------------

type FailureClass = "transient" | "local" | "systemic";

const TRANSIENT =
  /(429|rate.?limit|overloaded|too many requests|50[234]|bad gateway|ETIMEDOUT|ECONNRESET|ENOTFOUND|EAI_AGAIN|socket hang up|timed? ?out)/i;
const SYSTEMIC =
  /(401|unauthorized|invalid.{0,10}(api.?key|token)|authentication fail|bad credentials|credit balance|insufficient.{0,10}quota)/i;

function classify(e: unknown): FailureClass {
  // The whole text, not message()'s first line: runPhase() appends the
  // provider's own account of the failure below that line.
  const text = e instanceof Error ? e.message : String(e);
  // Transient wins a tie: a rate-limited 403 says "rate limit" too.
  if (TRANSIENT.test(text)) return "transient";
  if (SYSTEMIC.test(text)) return "systemic";
  return "local";
}

/** Sandcastle fails fast on provider errors; without this one 429 ends the run. */
async function withRetry<T>(label: string, fn: () => Promise<T> | T): Promise<T> {
  for (let attempt = 1; ; attempt++) {
    try {
      return await fn();
    } catch (e) {
      const kind = classify(e);
      if (kind === "systemic") {
        throw new IncompleteError(`${label} hit a systemic fault: ${message(e)}`);
      }
      if (kind === "local" || attempt > LIMITS.transientRetries) throw e;
      const waitMs = LIMITS.retryBaseMs * 2 ** (attempt - 1);
      console.error(
        `   ${label}: transient failure, retrying in ${waitMs / 1000}s ` +
          `(${attempt}/${LIMITS.transientRetries}): ${message(e)}`,
      );
      await sleep(waitMs);
    }
  }
}

const PHASE_TAIL_LINES = 25;

// Narrow by design: the rest of a phase log is the agent's own prose, which says
// "rate limit" and "timed out" often enough that classifying on the whole file
// would keep retrying a phase that was never going to succeed.
const PROVIDER_FAILURE =
  /^.*\b(?:API Error|Failed to authenticate|Invalid API key|OAuth|credit balance)\b.*$/gim;

/**
 * Sandcastle's AgentError carries the exit line, not the reason: a revoked token
 * arrives as "claude-code exited with code 1" with the 401 left in the phase log.
 * Puts the log's tail on the console and folds provider errors into the error
 * text, where classify() can see them.
 */
async function runPhase<T>(name: string, fn: () => Promise<T>): Promise<T> {
  try {
    return await fn();
  } catch (e) {
    let log: string;
    try {
      log = readFileSync(path.join(LOG_DIR, `${name}.log`), "utf8");
    } catch {
      throw e;
    }
    const tail = log.split("\n").filter(Boolean).slice(-PHASE_TAIL_LINES);
    console.error(`   ${name} failed. Last ${tail.length} line(s) of ${name}.log:`);
    for (const line of tail) console.error(`   | ${line}`);

    const provider = [...new Set((log.match(PROVIDER_FAILURE) ?? []).map((l) => l.trim()))];
    if (provider.length === 0) throw e;
    throw new Error([message(e), ...provider].join("\n"), { cause: e });
  }
}

// ---------------------------------------------------------------------------
// Frontier, computed here and never taken from an agent
// ---------------------------------------------------------------------------

function computeFrontier(): Frontier {
  return TRACKER === "github" ? githubFrontier() : localFrontier();
}

type GithubIssue = {
  number: number;
  title: string;
  labels: { name: string }[];
  body: string;
};

function githubFrontier(): Frontier {
  const candidates: GithubIssue[] = JSON.parse(
    sh(
      `gh issue list --state open --label "${SPEC_LABEL}"` +
        ` --json number,title,labels,body --limit 200`,
    ) || "[]",
  );

  const remaining: Ticket[] = [];
  const workable: Ticket[] = [];
  const excluded: Excluded[] = [];

  for (const issue of candidates) {
    const labels = issue.labels.map((l) => l.name);
    if (labels.includes("kind:spec") || labels.includes(LABELS.wontfix)) continue;
    if (!labels.includes(LABELS.readyForAgent)) continue;

    const ticket = { number: issue.number, title: issue.title, body: issue.body };
    remaining.push(ticket);

    const state = githubBlockerState(issue);
    if ("reason" in state) excluded.push({ number: issue.number, reason: state.reason });
    else if (state.open === 0) workable.push(ticket);
  }

  return { workable, remaining, excluded };
}

type BlockerState = { open: number } | { reason: string };

/**
 * Fails closed on an unreadable tracker, not on an undeclared dependency: no
 * declared blocker declares no blockers, but a failed API call declares nothing
 * and is skipped rather than dispatched.
 *
 * GitHub always returns `issue_dependencies_summary`, so the native count is
 * the answer on every repo and the body is read only to catch it contradicting
 * the link. The `refs` path below survives for a tracker that omits the field.
 */
function githubBlockerState(issue: GithubIssue): BlockerState {
  let full: {
    issue_dependencies_summary?: { blocked_by?: number };
    body?: string;
  };
  try {
    full = JSON.parse(sh(`gh api repos/{owner}/{repo}/issues/${issue.number}`));
  } catch (e) {
    return { reason: `blocker state unreadable: ${message(e)}` };
  }

  const refs = blockedByRefs(full.body ?? issue.body ?? "");
  const native = full.issue_dependencies_summary?.blocked_by;
  if (typeof native === "number") {
    if (native > 0) return { open: native };
    // The link says nothing gates this and the body says something does. A
    // human reading the issue believes the body, so the two answers are not
    // interchangeable and the loop has not established state.
    const contradicted = (refs ?? []).filter((ref) => !isClosedIssue(ref));
    if (contradicted.length > 0) {
      return {
        reason:
          `its body declares blocker(s) ${contradicted.map((n) => `#${n}`).join(", ")} ` +
          `that the tracker holds no dependency link for`,
      };
    }
    return { open: 0 };
  }

  if (!refs) return { reason: "its `Blocked by:` line could not be parsed" };

  let open = 0;
  for (const ref of refs) {
    try {
      if (sh(`gh api repos/{owner}/{repo}/issues/${ref} --jq .state`) !== "closed") open++;
    } catch (e) {
      return { reason: `blocker #${ref} unreadable: ${message(e)}` };
    }
  }
  return { open };
}

/** Unreadable counts as still gating: a blocker we cannot see is not one we can rule out. */
function isClosedIssue(ref: number): boolean {
  try {
    return sh(`gh api repos/{owner}/{repo}/issues/${ref} --jq .state`) === "closed";
  } catch {
    return false;
  }
}

/**
 * Both `**Blocked by:** 01: Title, 03: Other` and `Blocked by: #4, #9` name a
 * blocker at the start of each comma-separated segment, so only that is read;
 * scanning the line for digits would take the `2` from "Add OAuth2 support".
 *
 * `undefined` means unparseable, which callers treat as unverifiable rather
 * than unblocked.
 */
function blockedByRefs(body: string): number[] | undefined {
  // Two shapes reach here: the local ticket file's inline `**Blocked by:** …`,
  // and the issue template's `## Blocked by` heading over a bullet list. Reading
  // only the inline form silently returns "no blockers" for every issue.
  const inline = body.match(/^\**Blocked by:?\**[ \t]*(.*)$/im)?.[1];
  const afterHeading = body.split(/^#{1,6}[ \t]*Blocked by[ \t]*$/im)[1];
  const declaration = (inline || afterHeading?.split(/^#{1,6}[ \t]/m)[0] || "").trim();
  if (!declaration) return [];

  const refs: number[] = [];
  for (const segment of declaration.split(/[,;\n]|\band\b/)) {
    const named = segment.replace(/^[-*\s]+/, "").trim();
    if (!named) continue;
    if (/^(none|n\/a|nothing)\b/i.test(named)) continue;
    const ref = named.match(/^#?(\d+)\b/)?.[1];
    if (!ref) return undefined;
    refs.push(Number(ref));
  }
  return refs;
}

type LocalTicket = {
  title: string;
  status: string;
  body: string;
  blockedBy: number[] | undefined;
};

function localFrontier(): Frontier {
  const tickets = readLocalTickets(queueRef());

  const remaining: Ticket[] = [];
  const workable: Ticket[] = [];
  const excluded: Excluded[] = [];

  for (const [number, record] of [...tickets].sort((a, b) => a[0] - b[0])) {
    if (record.status !== LABELS.readyForAgent) continue;

    const ticket = { number, title: record.title, body: record.body };
    remaining.push(ticket);

    let open = 0;
    let unreadable = record.blockedBy ? undefined : "its `Blocked by:` line could not be parsed";
    for (const ref of record.blockedBy ?? []) {
      const blocker = tickets.get(ref);
      if (!blocker) {
        unreadable = `blocker ${ref} has no ticket file`;
        break;
      }
      if (blocker.status !== "closed") open++;
    }

    if (unreadable) excluded.push({ number, reason: unreadable });
    else if (open === 0) workable.push(ticket);
  }

  return { workable, remaining, excluded };
}

/**
 * The seed commit is the handover: before it the human's working copy is the
 * queue, after it the branch is, because that is where implementers record a
 * close. Reading the working tree afterwards redispatches closed tickets.
 * `null` means the working tree.
 */
function queueRef(): string | null {
  return branchExists(BRANCH) && ticketFilesAt(BRANCH).length > 0 ? BRANCH : null;
}

// Declarations, not `const` arrows: requireQueue() runs at module scope, well
// above this point, where a `const` would still be in its temporal dead zone.
function refName(ref: string | null): string {
  return ref ?? "your working tree";
}

function ticketsIn(files: string[]): string[] {
  return files.map((f) => f.trim()).filter((f) => /^\d+.*\.md$/.test(f));
}

function ticketFilesAt(ref: string | null): string[] {
  try {
    if (ref === null) return readdirSync(path.resolve(SCRATCH_ISSUES));
    return git(`ls-tree --name-only ${ref}:${SCRATCH_ISSUES}`).split("\n");
  } catch {
    return []; // no queue there
  }
}

/**
 * Puts the human's queue on the branch, so agents have a ticket to read and
 * somewhere to record closing it. Plumbing rather than a checkout, so the tree
 * and index the loop was launched from are untouched. Seeds all of
 * `.scratch/<slug>/`, where the implementer reads the spec beside the ticket, and
 * `--force`, since the queue is often gitignored. Runs no hooks, which is
 * acceptable for a commit that adds nothing outside `.scratch/`.
 */
function seedQueue(): void {
  const index = path.join(LOG_DIR, "seed-index");
  const staged = (args: string): string => sh(`GIT_INDEX_FILE=${index} git ${args}`);
  try {
    staged(`read-tree ${BRANCH}`);
    staged(`add --force -- ${SCRATCH_DIR}`);
    const commit = git(
      `commit-tree ${staged("write-tree")} -p ${BRANCH} ` +
        `-m "Seed the ${slug} ticket queue" -m "${DISCLAIMER}"`,
    );
    git(`update-ref refs/heads/${BRANCH} ${commit}`);
  } finally {
    rmSync(index, { force: true });
  }
}

/** Fails rather than warns: `--force` overrides a judgement call, not a missing queue. */
function requireQueue(): void {
  if (TRACKER !== "local") return;
  const ref = queueRef();
  if (ticketsIn(ticketFilesAt(ref)).length === 0) {
    fail(`No \`NN-*.md\` tickets for ${slug} in ${refName(ref)}: ${whyNoQueue(ref)}`);
  }
  if (ref === null) return; // nothing to drift from yet; the seed comes later

  // Blob hashes, not `git diff`: the queue lives only on the branch, so a diff
  // against the index reads every file as deleted and warns on every launch.
  const drifted = new Set<string>();
  try {
    const committed = new Map<string, string>();
    for (const line of git(`ls-tree ${ref}:${SCRATCH_ISSUES}`).split("\n")) {
      const m = line.match(/^\S+\s+blob\s+(\S+)\t(.+)$/);
      if (m) committed.set(m[2]!, m[1]!);
    }
    for (const f of ticketsIn(readdirSync(path.resolve(SCRATCH_ISSUES)))) {
      if (committed.get(f) !== git(`hash-object ${path.join(SCRATCH_ISSUES, f)}`)) {
        drifted.add(f);
      }
    }
  } catch {
    /* the drift check is advisory */
  }
  if (drifted.size > 0) {
    console.error(
      `Warning: your working tree and ${ref} disagree on ${[...drifted].sort().join(", ")}. ` +
        `The loop reads the branch, so those edits are ignored; commit them there, or ` +
        `delete ${ref} to restart the spec.`,
    );
  }
}

/**
 * Why `ticketFilesAt` came back empty. It swallows the read error, so a broken
 * repo and a wrong slug both arrive here looking identical; this re-reads
 * without the guard so the failure can be named.
 */
function whyNoQueue(ref: string | null): string {
  try {
    if (ref === null) readdirSync(path.resolve(SCRATCH_ISSUES));
    else git(`ls-tree --name-only ${ref}:${SCRATCH_ISSUES}`);
  } catch (e) {
    return message(e);
  }
  return "it holds no files named `NN-*.md`. Wrong slug?";
}

/** The one implementation of the local ticket format. */
function readLocalTickets(ref: string | null): Map<number, LocalTicket> {
  const tickets = new Map<number, LocalTicket>();
  for (const file of ticketsIn(ticketFilesAt(ref))) {
    const number = Number(file.match(/^(\d+)/)?.[1]);
    if (!Number.isFinite(number)) continue;
    const body =
      ref === null
        ? readFileSync(path.join(path.resolve(SCRATCH_ISSUES), file), "utf8")
        : git(`show ${ref}:${SCRATCH_ISSUES}/${file}`);
    const status = (body.match(/^\**Status:?\**\s*(.+)$/im)?.[1] ?? "").replace(/[`*]/g, "").trim();
    // `to-tickets` heads each file `# <NN>: <Title>`; the number is already
    // the key, so it is not part of the title. Dash forms are still accepted,
    // because queues written before the colon convention are still on disk.
    const title = (
      body.match(/^#\s+(.+)$/m)?.[1] ?? file.replace(/^\d+[-_]?/, "").replace(/\.md$/, "")
    )
      .replace(/^\d+\s*[:—–-]\s*/, "")
      .trim();
    tickets.set(number, { title, status, body, blockedBy: blockedByRefs(body) });
  }
  return tickets;
}

/**
 * Launch-time conditions no runtime guard catches, because they are about
 * whether the loop was aimed at the right thing at all. Everything else is
 * already bounded by the retry guards.
 */
function launchWarnings(frontier: Frontier): string[] {
  const warnings: string[] = [];

  if (frontier.excluded.length > 0) {
    warnings.push(
      `${frontier.excluded.length} ticket(s) could not be read, which usually means ` +
        `the tracker or the token is unhealthy rather than the tickets:\n` +
        frontier.excluded.map((e) => `     ${e.number}: ${e.reason}`).join("\n"),
    );
  }

  if (frontier.workable.length === 0) {
    warnings.push(
      frontier.remaining.length === 0
        ? `no open ${LABELS.readyForAgent} tickets carry ${SPEC_LABEL}: wrong slug, or nothing to do`
        : `${frontier.remaining.length} ticket(s) remain but none are workable: ` +
            `every one is blocked by work outside the loop`,
    );
  }

  // A stray .scratch directory silently wins over a live GitHub queue, and
  // nothing downstream would ever question it.
  if (TRACKER === "local") {
    try {
      const onGithub = JSON.parse(
        sh(`gh issue list --state open --label "${SPEC_LABEL}" --json number --limit 1`) || "[]",
      );
      if (onGithub.length > 0) {
        warnings.push(
          `${SCRATCH_ISSUES} made this a local run, but GitHub also has open ` +
            `${SPEC_LABEL} issues. Only one of them will be worked.`,
        );
      }
    } catch {
      /* no gh, no remote, no ambiguity */
    }
  }

  return warnings;
}

/**
 * `ref` is the *ticket* branch, not the shared one: this runs before
 * `fastForwardShared`, so the close has not reached the shared branch yet.
 */
function ticketIsClosed(ticket: number, ref: string): boolean {
  if (TRACKER === "github") {
    return sh(`gh api repos/{owner}/{repo}/issues/${ticket} --jq .state`) === "closed";
  }
  return readLocalTickets(ref).get(ticket)?.status === "closed";
}

// ---------------------------------------------------------------------------
// Branch lifecycle: each ticket runs on its own branch cut from the shared
// tip, so a bail-out cannot contaminate the tickets after it. Only a verified
// success advances the shared branch.
// ---------------------------------------------------------------------------

/**
 * Two disjoint namespaces, and the split is load-bearing. `-<N>` is cut and
 * recut locally and never pushed; `-wip-<N>` is where a bail-out is parked, and
 * is the only ticket branch that reaches origin. Overlap them and a published
 * branch leaves a `refs/remotes/origin/` ref behind that the next recut
 * silently resolves through; see dropTicketBranch.
 */
const ticketBranch = (ticket: number): string => `${BRANCH}-${ticket}`;
const wipBranch = (ticket: number): string => `${BRANCH}-wip-${ticket}`;

// Declarations, not `const` arrows: queueRef() reaches these from module scope
// well above this point, where a `const` would still be in its temporal dead
// zone.
function refExists(ref: string): boolean {
  try {
    git(`show-ref --verify --quiet ${ref}`);
    return true;
  } catch {
    return false;
  }
}

function branchExists(branch: string): boolean {
  return refExists(`refs/heads/${branch}`);
}

/**
 * Seeds whenever the branch carries no queue, not only when this call created
 * it, so a branch cut by hand to pick a different base is seeded too.
 */
function ensureSharedBranch(): void {
  if (!branchExists(BRANCH)) git(`branch ${BRANCH}`);
  if (TRACKER === "local" && ticketFilesAt(BRANCH).length === 0) seedQueue();
}

/** The worktree holding a branch, if one survived a previous run. */
function worktreeFor(branch: string): string | undefined {
  let listing: string;
  try {
    listing = git("worktree list --porcelain");
  } catch {
    return undefined;
  }
  for (const block of listing.split(/\n\s*\n/)) {
    if (new RegExp(`^branch refs/heads/${branch}$`, "m").test(block)) {
      return block.match(/^worktree (.+)$/m)?.[1];
    }
  }
  return undefined;
}

/**
 * Deletes the ref outright rather than via `git branch -d`, whose safety check
 * asks whether the branch merged into *HEAD*, the host checkout this loop
 * never touches. `fastForwardShared`'s ancestry assertion is the check that
 * matters.
 */
function dropTicketBranch(branch: string): void {
  removeWorktreeFor(branch);
  if (branchExists(branch)) git(`update-ref -d refs/heads/${branch}`);
  // Not housekeeping. `git worktree add <path> <branch>` resolves through
  // refs/remotes/origin/<branch> when the local head is gone, so a surviving
  // remote-tracking ref recuts the ticket from whatever was published there,
  // and sandcastle never sees the `invalid reference` that is its only route to
  // honouring baseBranch. The naming split above already makes that
  // unreachable; this covers a human or an older run having pushed `-<N>`.
  const remote = `refs/remotes/origin/${branch}`;
  if (refExists(remote)) git(`update-ref -d ${remote}`);
}

/** Split out of dropTicketBranch because parkBailOut needs it without the ref. */
function removeWorktreeFor(branch: string): void {
  const worktree = worktreeFor(branch);
  if (worktree) {
    try {
      git(`worktree remove --force ${worktree}`);
    } catch (e) {
      console.error(`   could not remove the worktree at ${worktree}: ${message(e)}`);
    }
  }
  try {
    git("worktree prune");
  } catch {
    /* pruning is opportunistic */
  }
}

/**
 * Advances the shared branch without checking anything out, so the host's working
 * tree is not ours to move. Always a fast-forward, since the loop is serial and
 * the ticket branch was cut from this tip; the assertion makes a surprise loud.
 */
function fastForwardShared(branch: string): void {
  git(`merge-base --is-ancestor ${BRANCH} ${branch}`);
  git(`update-ref refs/heads/${BRANCH} ${git(`rev-parse ${branch}`)}`);
}

/**
 * Commits what a failed run left behind, so the ticket branch carries the
 * partial work. Bypasses hooks: this is a quarantine branch that is never
 * merged, which is what those hooks protect the shared branch from.
 */
function snapshotBailOut(branch: string, ticket: number): void {
  const worktree = worktreeFor(branch);
  if (!worktree) {
    console.error(`   no worktree survived ticket ${ticket}; nothing to preserve`);
    return;
  }
  try {
    if (!sh(`git -C ${worktree} status --porcelain`)) return;
    sh(`git -C ${worktree} add -A`);
    // No tag: the driver runs on the host and cannot know the target repo's
    // commit vocabulary, and inventing one is worse than going without.
    sh(
      `git -C ${worktree} commit --no-verify -m "Snapshot bail-out for ticket ${ticket}" ` +
        `-m "Uncommitted work preserved by the to-done loop. Never merged." ` +
        `-m "${DISCLAIMER}"`,
    );
  } catch (e) {
    console.error(`   could not snapshot the bail-out for ticket ${ticket}: ${message(e)}`);
  }
}

/**
 * Renames a failed ticket branch to the `-wip-` name, which is the only one
 * publishWipBranches ever pushes. So a `-wip-` branch existing is itself the
 * signal that a ticket bailed out.
 */
function parkBailOut(branch: string, ticket: number): void {
  snapshotBailOut(branch, ticket);
  // Before the rename, not after: worktreeFor looks a worktree up by branch
  // name, so one still attached here follows the ref to `-wip-<N>`, and the
  // next attempt's dropTicketBranch then finds nothing to remove.
  removeWorktreeFor(branch);
  if (!branchExists(branch)) return;
  const parked = wipBranch(ticket);
  try {
    // update-ref, matching dropTicketBranch, and it overwrites, which is what a
    // second bail-out of the same ticket in one run needs.
    git(`update-ref refs/heads/${parked} ${git(`rev-parse ${branch}`)}`);
    git(`update-ref -d refs/heads/${branch}`);
  } catch (e) {
    console.error(`   could not park ticket ${ticket} as ${parked}: ${message(e)}`);
  }
}

function localWipBranches(): string[] {
  try {
    return git(`branch --list "${BRANCH}-wip-*" --format='%(refname:short)'`)
      .split("\n")
      .map((b) => b.trim())
      .filter(Boolean);
  } catch (e) {
    console.error(`   could not list bail-out branches: ${message(e)}`);
    return [];
  }
}

/** Bail-out branches reach the remote once, at finalize. */
function publishWipBranches(): string[] {
  const published: string[] = [];
  for (const branch of localWipBranches()) {
    try {
      // Force-with-lease: a retry recuts the branch, replacing its history.
      git(`push --force-with-lease origin ${branch}`);
      published.push(branch);
    } catch (e) {
      console.error(`   could not push ${branch}: ${message(e)}`);
    }
  }
  return published;
}

// ---------------------------------------------------------------------------
// Phases
// ---------------------------------------------------------------------------

const rankingSchema = z.object({
  order: z.array(z.number()),
  error: z.object({ code: z.string(), message: z.string() }).optional(),
});

/**
 * Ranking is an optimisation, not a correctness gate: every workable ticket is
 * safe to start, so any planner failure costs only creation order.
 */
async function runPlanner(workable: Ticket[]): Promise<Ticket[]> {
  if (workable.length <= 1) return workable;

  const fallback = (why: string): Ticket[] => {
    console.error(`   planner fell back to creation order: ${why}`);
    return workable;
  };

  let order: number[];
  try {
    const result = await runPhase("planner", () =>
      run({
        sandbox: phaseSandbox(),
        ...phaseOpts({ branch: BRANCH, deps: false }),
        name: "planner",
        agent: claudeCode(MODELS.planner),
        promptFile: promptPath("planner.md"),
        promptArgs: {
          SPEC_SLUG: slug,
          WORKABLE: JSON.stringify(workable),
          DISCIPLINE,
        },
        maxIterations: LIMITS.plannerMaxIter,
        completionSignal: COMPLETION_SIGNAL,
        output: Output.object({
          tag: "plan",
          schema: rankingSchema,
          maxRetries: 1,
        }),
        logging: logging("planner"),
      }),
    );
    if (result.output.error) {
      return fallback(`${result.output.error.code}: ${result.output.error.message}`);
    }
    order = result.output.order;
  } catch (e) {
    return fallback(message(e));
  }

  const offered = workable.map((t) => t.number).sort((a, b) => a - b);
  const returned = [...order].sort((a, b) => a - b);
  if (returned.length !== offered.length || returned.some((n, i) => n !== offered[i])) {
    return fallback("the ranking was not a permutation of the workable set");
  }
  return order.map((n) => workable.find((t) => t.number === n)!);
}

const outcomeSchema = z.object({
  result: z.enum(["closed", "bailed"]),
  reason: z.string(),
});

async function runImplementer(ticket: number, attempt: number, branch: string) {
  return runPhase(`implementer-${ticket}`, () =>
    run({
      sandbox: phaseSandbox(),
      ...phaseOpts({ branch, base: BRANCH, deps: true }),
      name: `implementer-${ticket}`,
      agent: claudeCode(MODELS.implementer),
      promptFile: promptPath("implementer.md"),
      promptArgs: {
        TICKET: String(ticket),
        SPEC_SLUG: slug,
        TRACKER,
        BRANCH: branch,
        ATTEMPT: String(attempt),
        DISCIPLINE,
        DISCLAIMER,
      },
      maxIterations: LIMITS.implementerMaxIter,
      idleTimeoutSeconds: LIMITS.implementerIdleSeconds,
      completionSignal: COMPLETION_SIGNAL,
      output: Output.object({
        tag: "outcome",
        schema: outcomeSchema,
        maxRetries: 1,
      }),
      logging: logging(`implementer-${ticket}`),
    }),
  );
}

/** A self-report of success is an input to this, not the answer. */
function implementerPostcondition(
  ticket: number,
  result: Awaited<ReturnType<typeof runImplementer>>,
  branch: string,
): string | undefined {
  if (result.output.result === "bailed") return `bailed out: ${result.output.reason}`;
  if (result.commits.length === 0) return "reported the ticket closed but committed nothing";
  if (result.preservedWorktreePath) {
    return `left uncommitted changes in ${result.preservedWorktreePath}`;
  }
  try {
    if (!ticketIsClosed(ticket, branch)) return "reported the ticket closed but it is still open";
  } catch (e) {
    return `could not confirm the ticket closed: ${message(e)}`;
  }
  return undefined;
}

async function runPrComposer(
  mode: "complete" | "partial",
  reason: string,
  frontier: Frontier,
  wipBranches: string[],
  assignee: string,
): Promise<void> {
  await runPhase("pr-composer", () =>
    run({
      sandbox: phaseSandbox(),
      ...phaseOpts({ branch: BRANCH, deps: false }),
      name: "pr-composer",
      agent: claudeCode(MODELS.prComposer),
      promptFile: promptPath("pr-composer.md"),
      promptArgs: {
        SPEC_SLUG: slug,
        TRACKER,
        BRANCH,
        MODE: mode,
        INCOMPLETE_REASON: reason,
        REMAINING: JSON.stringify(titlesOnly(frontier.remaining)),
        EXCLUDED: JSON.stringify(frontier.excluded),
        WIP_BRANCHES: JSON.stringify(wipBranches),
        SPEC_LABEL,
        STALLED_LABEL: LABELS.needsInfo,
        ASSIGNEE: assignee,
        DISCIPLINE,
      },
      maxIterations: LIMITS.prComposerMaxIter,
      completionSignal: COMPLETION_SIGNAL,
      logging: logging("pr-composer"),
    }),
  );
}

async function runPrReviewer(pr: number): Promise<void> {
  // The one phase that requires codex rather than merely carrying it, so the
  // refusal lives here. Read once and handed to phaseSandbox below, so the
  // check and the container it gates see the same credential.
  const codex = resolveCodexCredential();
  if (codex.problem) {
    fail(
      `Cannot review PR #${pr}: ${codex.problem}.\n` +
        `Fix that, then run the review on its own: loop.mts ${slug} review`,
    );
  }

  await runPhase("pr-reviewer", () =>
    run({
      sandbox: phaseSandbox(codex),
      ...phaseOpts({ branch: BRANCH, deps: true }),
      name: "pr-reviewer",
      agent: claudeCode(MODELS.prReviewer),
      promptFile: promptPath("pr-reviewer.md"),
      promptArgs: {
        SPEC_SLUG: slug,
        BRANCH,
        PR: String(pr),
        REVIEW_MARKER,
        STALLED_LABEL: LABELS.needsInfo,
        HANDOFF_LABEL: LABELS.readyForHuman,
        DISCIPLINE,
        DISCLAIMER,
      },
      maxIterations: LIMITS.reviewerMaxIter,
      completionSignal: COMPLETION_SIGNAL,
      logging: logging("pr-reviewer"),
    }),
  );

  // pr-reviewer.md forbids the reviewer pushing, and its accepted fixes are
  // commits on the shared branch. Here rather than in the callers, so the
  // standalone `review` phase cannot leave them local.
  await withRetry("push", () => git(`push origin ${BRANCH}`));
}

type PullRequest = {
  number: number;
  isDraft: boolean;
  headRefOid: string;
  labels: { name: string }[];
  assignees: { login: string }[];
};

function findPr(): PullRequest | undefined {
  const found: PullRequest[] = JSON.parse(
    sh(
      `gh pr list --head "${BRANCH}" --state open` +
        ` --json number,isDraft,headRefOid,labels,assignees --limit 1`,
    ) || "[]",
  );
  return found[0];
}

const hasLabel = (pr: PullRequest, name: string): boolean => pr.labels.some((l) => l.name === name);

/**
 * A PR nobody is told about is a PR nobody reviews. Checked right after the
 * composer applies it all, so a missing signal can still be retried.
 */
function prPostcondition(assignee: string): {
  pr?: PullRequest;
  failure?: string;
} {
  let pr: PullRequest | undefined;
  try {
    pr = findPr();
  } catch (e) {
    return { failure: `could not check for the pull request: ${message(e)}` };
  }
  if (!pr) return { failure: `no open pull request for ${BRANCH}` };

  const missing: string[] = [];
  if (pr.headRefOid !== git(`rev-parse ${BRANCH}`)) missing.push("the branch tip");
  if (!hasLabel(pr, SPEC_LABEL)) missing.push(`the \`${SPEC_LABEL}\` label`);
  if (!hasLabel(pr, LABELS.needsInfo)) missing.push(`the \`${LABELS.needsInfo}\` label`);
  if (assignee && !pr.assignees.some((a) => a.login === assignee)) {
    missing.push(`an assignment to @${assignee}`);
  }

  return missing.length === 0
    ? { pr }
    : { pr, failure: `PR #${pr.number} is missing ${missing.join(" and ")}` };
}

/** The login the PR is handed to: the owner of the token that opened it. */
function tokenOwner(): string {
  try {
    return sh("gh api user --jq .login");
  } catch (e) {
    console.error(`   could not resolve who to hand the PR to: ${message(e)}`);
    return "";
  }
}

/**
 * The verdict, and the promotion out of the stalled state. A review that dies
 * partway leaves the PR at `needs-info`, which is exactly what it is.
 */
function reviewPostcondition(number: number): string | undefined {
  let comments: { body: string }[];
  let pr: PullRequest | undefined;
  try {
    comments = JSON.parse(sh(`gh pr view ${number} --json comments --jq .comments`) || "[]");
    pr = findPr();
  } catch (e) {
    return `could not check the review outcome: ${message(e)}`;
  }

  const missing: string[] = [];
  if (pr && pr.headRefOid !== git(`rev-parse ${BRANCH}`)) missing.push("the branch tip");

  const verdict = comments.find((c) => c.body.includes(REVIEW_MARKER));
  if (!verdict) missing.push("a verdict comment");
  else {
    // The cross-check runs in a container worktree that is destroyed, and its
    // audit record is git-excluded, so the verdict comment is the only place
    // the loop can observe whether an independent review happened at all.
    const crossCheck = verdict.body.match(/^Cross-check:\s*(.+)$/m)?.[1]?.trim();
    if (!crossCheck) missing.push("a `Cross-check:` line in the verdict");
    else if (!/^performed\b/i.test(crossCheck)) {
      missing.push(`an independent cross-check: ${crossCheck}`);
    }
  }

  if (pr && !hasLabel(pr, LABELS.readyForHuman)) {
    missing.push(`the \`${LABELS.readyForHuman}\` label`);
  }
  if (pr && hasLabel(pr, LABELS.needsInfo)) {
    missing.push(`removal of the \`${LABELS.needsInfo}\` label`);
  }

  return missing.length === 0
    ? undefined
    : `PR #${number} is missing ${missing.join(" and ")}, so it stays a stalled PR`;
}

async function finalize(
  mode: "complete" | "partial",
  frontier: Frontier,
  reason = "",
): Promise<void> {
  const wipBranches = publishWipBranches();
  const assignee = tokenOwner();

  await withRetry("push", () => git(`push origin ${BRANCH}`));
  await withRetry("pr-composer", () =>
    runPrComposer(mode, reason, frontier, wipBranches, assignee),
  );

  // Every PR lands stalled, whatever ended the run; only a finished review
  // promotes it. So a run that dies anywhere still leaves an accurate signal.
  const { pr, failure } = prPostcondition(assignee);
  if (failure) console.error(`   ${failure}`);
  if (!pr) return;
  console.error(`PR #${pr.number}${pr.isDraft ? " (draft)" : ""}`);

  if (mode === "partial") {
    console.error(`Stopped early. PR #${pr.number} left at \`${LABELS.needsInfo}\`.`);
    return;
  }

  await withRetry("pr-reviewer", () => runPrReviewer(pr.number));

  const missing = reviewPostcondition(pr.number);
  if (missing) console.error(`   ${missing}`);
  else console.error(`Handed to ${assignee ? `@${assignee}` : LABELS.readyForHuman}.`);
}

// ---------------------------------------------------------------------------
// The loop
// ---------------------------------------------------------------------------

async function auto(): Promise<void> {
  const startedAt = Date.now();
  const tries = new Map<number, number>();
  let consecutiveFailures = 0;
  let frontier = computeFrontier();
  let finalized = false;

  // Refuse the wrong launches, rather than confirming every right one.
  const warnings = launchWarnings(frontier);
  if (warnings.length > 0 && !force) {
    fail(
      `Refusing to start:\n${warnings.map((w) => `   - ${w}`).join("\n")}\n\n` +
        `Run \`loop.mts ${slug} plan\` to inspect, or re-run with --force to go anyway.`,
    );
  }

  ensureSharedBranch();

  try {
    for (let i = 0; i < LIMITS.outerIter; i++) {
      if (Date.now() - startedAt > LIMITS.wallTimeMs) {
        throw new IncompleteError(
          `wall-time limit of ${LIMITS.wallTimeMs / 3_600_000}h reached after ${i} ticket(s)`,
        );
      }

      frontier = await withRetry("frontier", computeFrontier);
      for (const { number, reason } of frontier.excluded) {
        console.error(`   skipping ticket ${number}: ${reason}`);
      }

      if (frontier.workable.length === 0) {
        if (frontier.remaining.length === 0) {
          console.error("Queue drained.");
          finalized = true;
          await finalize("complete", frontier);
          return;
        }
        throw new IncompleteError(
          `${frontier.remaining.length} agent-ready ticket(s) remain, none workable: ` +
            `blocked by work outside the loop, or their state could not be read`,
        );
      }

      const ticket = (await runPlanner(frontier.workable))[0]!;

      const attempt = (tries.get(ticket.number) ?? 0) + 1;
      tries.set(ticket.number, attempt);
      if (attempt > LIMITS.ticketTries) {
        throw new IncompleteError(
          `ticket ${ticket.number} was dispatched ${LIMITS.ticketTries} times ` +
            `and is still workable: stuck`,
        );
      }

      console.error(
        `→ ticket ${ticket.number} (attempt ${attempt}/${LIMITS.ticketTries}): ${ticket.title}`,
      );

      // Recut from the current tip: a retry must not inherit the tree that
      // the previous attempt failed on.
      const branch = ticketBranch(ticket.number);
      dropTicketBranch(branch);

      let failed: string | undefined;
      try {
        const result = await withRetry(`implementer-${ticket.number}`, () =>
          runImplementer(ticket.number, attempt, branch),
        );
        failed = implementerPostcondition(ticket.number, result, branch);
      } catch (e) {
        if (e instanceof IncompleteError) throw e;
        failed = message(e);
      }

      if (!failed) {
        fastForwardShared(branch);
        await withRetry("push", () => git(`push origin ${BRANCH}`));
        dropTicketBranch(branch);
        consecutiveFailures = 0;
        continue;
      }

      // The work survives on the parked branch, carrying whatever was reached.
      parkBailOut(branch, ticket.number);
      consecutiveFailures++;
      console.error(`   ticket ${ticket.number} did not close: ${failed}`);
      if (consecutiveFailures >= LIMITS.consecutiveFailures) {
        throw new IncompleteError(
          `${consecutiveFailures} tickets in a row failed to close: ` +
            `the environment is likely broken, not the tickets`,
        );
      }
    }

    throw new IncompleteError(`ticket limit of ${LIMITS.outerIter} reached`);
  } catch (e) {
    if (!(e instanceof IncompleteError)) throw e;
    console.error(`Incomplete: ${e.message}`);
    if (!finalized) {
      try {
        await finalize("partial", frontier, e.message);
      } catch (finalizeError) {
        console.error(`Could not file the partial PR: ${message(finalizeError)}`);
      }
    }
    throw e;
  }
}

// ---------------------------------------------------------------------------
// Preflight
// ---------------------------------------------------------------------------

/**
 * Canonical triage roles to this repo's actual label strings. Guessing when the
 * map is missing would enumerate zero tickets and declare the queue drained.
 */
function resolveLabels(): {
  readyForAgent: string;
  readyForHuman: string;
  needsInfo: string;
  wontfix: string;
} {
  if (!existsSync(TRIAGE_DOC)) {
    fail(
      `${TRIAGE_DOC} not found; the loop cannot tell which labels this repo uses.\n` +
        `Run /setup-repo-skills in this repo first.`,
    );
  }
  const doc = readFileSync(TRIAGE_DOC, "utf8");
  const lookup = (role: string): string => {
    const actual = doc
      .match(new RegExp(`^\\|\\s*\`${role}\`\\s*\\|\\s*\`([^\`]+)\`\\s*\\|`, "m"))?.[1]
      ?.trim();
    return actual ?? fail(`${TRIAGE_DOC} does not map the ${role} role.`);
  };
  return {
    readyForAgent: lookup("ready-for-agent"),
    readyForHuman: lookup("ready-for-human"),
    needsInfo: lookup("needs-info"),
    wontfix: lookup("wontfix"),
  };
}

// A declaration, not a `const`: resolveCredentials() runs at module scope far
// above this line, where a `const` would still be in its temporal dead zone,
// which `tsc` does not catch.
function isMetered(name: string): boolean {
  return name === "ANTHROPIC_API_KEY" || name === "OPENAI_API_KEY";
}

/**
 * Credentials come from `.to-done/secrets` and nowhere else: one file, written
 * once. An agent launching this skill cannot see the human's exported
 * variables, so an environment fallback would work for some launches and not
 * others, which is worse than not having one.
 *
 * Names are most-preferred first, subscription before API key, because metered
 * billing across a six-hour run is the expensive mistake, and only the
 * preferred one reaches the container. Claude Code has no login step, so
 * withholding the rest is the only thing stopping an expired token from
 * silently billing per token for a whole run.
 *
 * Codex is not here. Its credential is a live file rather than a value in this
 * one; resolveCodexCredential() reads it, and only the review phase gets it.
 */
function resolveCredentials(): {
  env: Record<string, string>;
  using: string[];
} {
  if (!existsSync(SECRETS_FILE)) {
    fail(
      `${SECRETS_FILE} not found. Copy the template and fill it in:\n` +
        `  mkdir -p .to-done\n` +
        `  cp ${path.join(SKILL_DIR, "secrets.example")} .to-done/secrets\n` +
        `  chmod 600 .to-done/secrets\n` +
        `It must stay gitignored; .to-done/.gitignore is where that rule belongs.`,
    );
  }
  const secrets = parseEnvFile(SECRETS_FILE);

  const env: Record<string, string> = {};
  const using: string[] = [];
  const missing: string[] = [];

  const take = (names: string[]): void => {
    const found = names.find((n) => secrets[n]?.trim());
    if (!found) {
      missing.push(names.join(" or "));
      return;
    }
    env[found] = secrets[found]!.trim();
    // "This run bills per token" is worth seeing before six hours of it.
    using.push(isMetered(found) ? `${found} (metered)` : found);
  };

  take(["GH_TOKEN"]);
  take(["CLAUDE_CODE_OAUTH_TOKEN", "ANTHROPIC_API_KEY"]);

  if (secrets.CODEX_AUTH_JSON?.trim()) {
    console.error(
      `Warning: ${SECRETS_FILE} sets CODEX_AUTH_JSON, which is now ignored. The loop reads the\n` +
        `  live credential itself at review time. Delete the line, and the stale token with it.`,
    );
  }

  if (missing.length > 0) {
    fail(`${SECRETS_FILE} sets no ${missing.join(", and no ")}.`);
  }

  // The driver's own `gh` calls run on the host. Without this they act as
  // whoever the host is logged in as, usually a broader scope than this
  // repo-scoped PAT. `git push` is unaffected unless the remote is HTTPS and
  // gh's credential helper is configured, in which case it follows the same
  // token. Nothing else from `secrets` is put in this process's environment.
  process.env.GH_TOKEN = env.GH_TOKEN;
  return { env, using };
}

/** What the review phase will run codex with. Resolved fresh at every read. */
type CodexCredential = {
  /** Injected into the review sandbox. Empty when nothing usable resolved. */
  env: Record<string, string>;
  /** The startup banner's account of which credential this is. */
  label: string;
  /** Epoch ms the access token expires, when the credential carries one. */
  expiresAt?: number;
  /** Why there is nothing usable, when there is not. */
  problem?: string;
};

/**
 * Codex sits outside resolveCredentials() because it is not a value in
 * `.to-done/secrets`: it is a live file the host's own `codex login`
 * maintains. Pasting a copy into `secrets` is what let a 12-day-old token
 * against a 10-day lifetime look healthy for a whole run, so this reads the
 * real file, every time it is asked, and never writes back to `secrets`.
 *
 * The choice is made by what is configured, never by observing a rejection:
 * `codex login status` is a local file check that passes for any well-formed
 * `auth.json`, so there is no rejection to observe from here.
 */
function resolveCodexCredential(): CodexCredential {
  const secrets = parseEnvFile(SECRETS_FILE);

  // Static: no refresh, no rotation, nothing to preflight. It wins when set,
  // and every run then bills.
  const key = secrets.OPENAI_API_KEY?.trim();
  if (key) return { env: { OPENAI_API_KEY: key }, label: "OPENAI_API_KEY (metered)" };

  const configured = secrets.CODEX_AUTH_FILE?.trim() || "~/.codex/auth.json";
  const file = configured.startsWith("~/")
    ? path.join(homedir(), configured.slice(2))
    : path.resolve(configured);
  const none = (problem: string): CodexCredential => ({ env: {}, label: "none", problem });

  if (!existsSync(file)) return none(`${file} does not exist; run \`codex login\``);

  let auth: unknown;
  try {
    auth = JSON.parse(readFileSync(file, "utf8"));
  } catch (e) {
    return none(`${file} is not readable JSON: ${message(e)}`);
  }

  const expiresAt = accessTokenExpiry(auth);
  if (expiresAt !== undefined && expiresAt <= Date.now()) {
    return none(
      `the access token in ${file} expired ${humanDuration(Date.now() - expiresAt)} ago, and ` +
        `clearing that needs an interactive \`codex login\`, which the loop cannot run`,
    );
  }

  // Re-serialised compact, which is what the container's auth.json wants and
  // what proves the file parsed.
  return {
    env: { CODEX_AUTH_JSON: JSON.stringify(auth) },
    label:
      expiresAt === undefined ? file : `${file} (${humanDuration(expiresAt - Date.now())} left)`,
    expiresAt,
  };
}

/**
 * A local decode, no network call, so there is no chance of spending the
 * refresh token here and orphaning the host's own login. ChatGPT-mode access
 * tokens live ten days. `id_token` expires hourly and is a short-lived
 * identity assertion rather than the API credential, so it is not read.
 */
function accessTokenExpiry(auth: unknown): number | undefined {
  const token = (auth as { tokens?: { access_token?: unknown } } | null)?.tokens?.access_token;
  if (typeof token !== "string") return undefined;
  const payload = token.split(".")[1];
  if (!payload) return undefined;
  try {
    const { exp } = JSON.parse(Buffer.from(payload, "base64url").toString("utf8"));
    return typeof exp === "number" ? exp * 1000 : undefined;
  } catch {
    return undefined; // Not a JWT we can read; the reviewer still gets to try.
  }
}

function humanDuration(ms: number): string {
  const hours = Math.max(0, Math.round(ms / 3_600_000));
  return hours >= 48 ? `${Math.round(hours / 24)}d` : `${hours}h`;
}

/**
 * A forecast, not a gate: the review is hours away and re-reads the credential
 * itself. Saying so at minute one is what turns a cross-check the run silently
 * lost into something a human can still act on.
 */
function reportCodexCredential(): void {
  const codex = resolveCodexCredential();
  console.error(`Codex: ${codex.label}`);
  if (codex.problem) {
    console.error(`Warning: ${codex.problem}.\n  The review phase will refuse to start.`);
    return;
  }
  if (codex.expiresAt === undefined) return;
  const left = codex.expiresAt - Date.now();
  if (left < LIMITS.wallTimeMs) {
    console.error(
      `Warning: the codex credential expires in ${humanDuration(left)}, inside this run's ` +
        `${LIMITS.wallTimeMs / 3_600_000}h window.\n` +
        `  codex would then refresh it inside a container, and refresh tokens are single-use, so\n` +
        `  that rotation orphans your host login. Run \`codex login\` first.`,
    );
  }
}

/**
 * `codex login --with-access-token` is deliberately unused: it wants a
 * Business/Enterprise workspace token, not anything a personal `auth.json`
 * holds. There is no success gate either, because the only available one,
 * `codex login status`, passes for any well-formed file. Expiry is caught on
 * the host by resolveCodexCredential(); a credential the API refuses at review
 * time surfaces as `Cross-check: unavailable` in the verdict, which
 * reviewPostcondition refuses to promote.
 *
 * Runs in every container, so any phase can reach for codex, and it is a no-op
 * when no credential resolved. Fatal when it fails, because a credential that
 * was resolved on the host and then would not install is a broken container
 * rather than a missing feature.
 */
function codexLoginCommand(): string {
  return [
    'if [ -n "$OPENAI_API_KEY" ]; then',
    "  printenv OPENAI_API_KEY | codex login --with-api-key;",
    'elif [ -n "$CODEX_AUTH_JSON" ]; then',
    '  mkdir -p "$HOME/.codex"',
    '    && printenv CODEX_AUTH_JSON > "$HOME/.codex/auth.json"',
    '    && chmod 600 "$HOME/.codex/auth.json";',
    "fi",
  ].join(" ");
}

/** Docker tag for the repo the loop was launched against. */
function repoTag(): string {
  let root: string;
  try {
    root = sh("git rev-parse --show-toplevel");
  } catch {
    root = process.cwd();
  }
  return path
    .basename(root)
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, "-");
}

/** `KEY=value` lines; comments and blanks skipped. */
function parseEnvFile(file: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(file)) return out;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    if (/^\s*(#|$)/.test(line)) continue;
    const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) {
      console.error(`Warning: ignoring unparseable line in ${file}: ${line.trim()}`);
      continue;
    }
    out[match[1]!] = match[2]!.trim().replace(/^(['"])([\s\S]*)\1$/, "$2");
  }
  return out;
}

/** Tuning only. The host environment wins, so a one-off override still works. */
function loadConfig(): void {
  for (const [key, value] of Object.entries(parseEnvFile(path.resolve(".to-done", "config")))) {
    if (process.env[key] === undefined) process.env[key] = value;
  }
}

function requireImage(): void {
  try {
    sh(`docker image inspect ${IMAGE_NAME}`);
  } catch (e) {
    const why = message(e);
    // A stopped daemon fails this same call, and "build the image" is useless
    // advice for it.
    if (/cannot connect|daemon|permission denied/i.test(why)) {
      fail(`Docker is not reachable:\n${why}`);
    }
    fail(
      `Docker image "${IMAGE_NAME}" not found. Build it with:\n` +
        `  ${path.join(SKILL_DIR, "scripts/build-image.sh")}`,
    );
  }
  warnIfImageStale();
  warnIfNodeAbiDiffers();
}

/**
 * The host `node_modules` is copied into every worktree, so a native addon
 * built against the host's Node gets loaded by the image's. Nothing downstream
 * catches it: the copy succeeds, and the failure surfaces as the repo's own
 * suite throwing from a package no ticket touched.
 */
function warnIfNodeAbiDiffers(): void {
  if (!existsSync(path.resolve("node_modules"))) return;
  let image: string;
  try {
    image = sh(`docker run --rm --entrypoint node ${IMAGE_NAME} -p process.versions.modules`);
  } catch {
    return; // A diagnostic must never be the reason a run does not start.
  }
  if (image === process.versions.modules) return;
  console.error(
    `Warning: this host builds native modules for Node ABI ${process.versions.modules}; ` +
      `"${IMAGE_NAME}" runs ABI ${image}.\n` +
      `  node_modules is copied from here into every worktree, so any dependency with an\n` +
      `  ABI-bound binary will fail to load in the sandbox. N-API packages are unaffected.\n` +
      `  Rebuild the ones that are not, from TO_DONE_SETUP: \`pnpm rebuild <pkg>\`.`,
  );
}

/** Skills are baked at a commit, so an old image runs an old `/implement`. */
function warnIfImageStale(): void {
  let baked: string;
  let head: string;
  try {
    baked = sh(
      `docker image inspect ${IMAGE_NAME} --format '{{index .Config.Labels "to-done.skills-sha"}}'`,
    );
    head = sh(`git -C ${SKILL_DIR} rev-parse HEAD`);
  } catch {
    return; // A diagnostic must never be the reason a run does not start.
  }
  const rebuild = `  Rebuild: ${path.join(SKILL_DIR, "scripts/build-image.sh")}`;
  if (!baked || baked === "<no value>") {
    console.error(`Warning: "${IMAGE_NAME}" carries no skills-sha label.\n${rebuild}`);
  } else if (baked !== head) {
    console.error(
      `Warning: "${IMAGE_NAME}" bakes skills ${baked.slice(0, 7)}; the skills repo is at ${head.slice(0, 7)}.\n` +
        `  Skill edits since then are not in the image.\n${rebuild}`,
    );
  }

  // Shas alone are not enough: the build resolves the ref from the *remote*, so
  // an uncommitted edit leaves the label equal to HEAD and the check above
  // silent. Repo-wide under `skills/`, because the build installs `--all`.
  try {
    const root = sh(`git -C ${SKILL_DIR} rev-parse --show-toplevel`);
    const dirty = sh(`git -C ${root} status --porcelain -- skills`);
    if (dirty) {
      console.error(
        `Warning: ${dirty.split("\n").length} uncommitted change(s) under ${root}/skills.\n` +
          `  The image installs skills from the remote at a commit, so these are in no image.\n` +
          `  Commit and push them, then rebuild.`,
      );
    } else if (sh(`git -C ${SKILL_DIR} branch -r --contains ${head}`).trim() === "") {
      console.error(
        `Warning: skills commit ${head.slice(0, 7)} is not on any remote branch.\n` +
          `  The image build resolves it from the remote, so it would fail or bake an older tree.\n` +
          `  Push it, then rebuild.`,
      );
    }
  } catch {
    /* still only a diagnostic */
  }
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(all: string[]): {
  slug: string;
  phase: string;
  phaseArg?: string;
  force: boolean;
} {
  const argv = all.filter((a) => !a.startsWith("--"));
  const force = all.includes("--force");
  const unknown = all.filter((a) => a.startsWith("--") && a !== "--force");
  if (unknown.length > 0) fail(`Unknown option: ${unknown[0]}\n${USAGE}`);

  const [slug, phase = "auto", phaseArg] = argv;
  if (!slug || slug.startsWith("-")) fail(USAGE);
  if (!["auto", "plan", "implement", "pr", "review"].includes(phase)) {
    fail(`Unknown phase: ${phase}\n${USAGE}`);
  }
  if (phase === "implement" && !Number.isFinite(Number(phaseArg))) {
    fail("Usage: loop.mts <slug> implement <ticket>");
  }
  return { slug: slug!, phase, phaseArg, force };
}

async function main(): Promise<void> {
  switch (phase) {
    case "auto":
      return auto();

    case "plan": {
      const frontier = computeFrontier();
      const warnings = launchWarnings(frontier);
      const ranked = frontier.workable.length > 0 ? await runPlanner(frontier.workable) : [];
      console.log(
        JSON.stringify(
          {
            ...frontier,
            workable: titlesOnly(ranked),
            remaining: titlesOnly(frontier.remaining),
            warnings,
          },
          null,
          2,
        ),
      );
      return;
    }

    case "implement": {
      const ticket = Number(phaseArg);
      const branch = ticketBranch(ticket);
      ensureSharedBranch();
      dropTicketBranch(branch);
      const result = await runImplementer(ticket, 1, branch);
      const failure = implementerPostcondition(ticket, result, branch);
      if (failure) {
        parkBailOut(branch, ticket);
        fail(`ticket ${ticket} did not close: ${failure}`);
      }
      fastForwardShared(branch);
      dropTicketBranch(branch);
      console.log(JSON.stringify(result.output, null, 2));
      return;
    }

    case "pr": {
      const frontier = computeFrontier();
      const mode = frontier.remaining.length === 0 ? "complete" : "partial";
      const assignee = tokenOwner();
      await runPrComposer(
        mode,
        mode === "partial" ? "run by hand" : "",
        frontier,
        localWipBranches(),
        assignee,
      );
      const { failure } = prPostcondition(assignee);
      if (failure) fail(failure);
      return;
    }

    case "review": {
      const pr = findPr();
      if (!pr) fail(`No open pull request for ${BRANCH}.`);
      await runPrReviewer(pr!.number);
      const missing = reviewPostcondition(pr!.number);
      if (missing) fail(missing);
      return;
    }
  }
}

try {
  await main();
} catch (e) {
  if (e instanceof IncompleteError) process.exit(1);
  console.error(message(e));
  if (e instanceof Error && e.stack) console.error(e.stack);
  process.exit(2);
}
