import { test } from "node:test";
import assert from "node:assert/strict";
import { execSync } from "node:child_process";
import { chmodSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { branchExists, worktreeFor } from "./branches.mts";
import {
  bailOutMessage,
  publishStuckBranches,
  saveBailOut,
  stuckTickets,
  type Save,
  type SaveCtx,
} from "./save.mts";

const SHARED = "agent/spec";
const DISCLAIMER = "_Generated by an AI agent._";
const ctx = (tracker: "github" | "local"): SaveCtx => ({ tracker, shared: SHARED, disclaimer: DISCLAIMER });
const save = (over: Partial<Save> = {}): Save => ({ reason: "stuck on X", attempt: 1, tries: 3, ...over });

const cwd0 = process.cwd();
const trash: string[] = [];

const G = (dir: string, cmd: string): string =>
  execSync(`git -C ${dir} ${cmd}`, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();

/** A fresh repo with a `main` seed commit and the shared branch cut from it. */
function makeRepo(): string {
  const repo = mkdtempSync(path.join(tmpdir(), "to-done-repo-"));
  trash.push(repo);
  G(repo, "init -q -b main");
  G(repo, "config user.email t@example.com");
  G(repo, "config user.name Tester");
  G(repo, "config commit.gpgsign false");
  writeFileSync(path.join(repo, "seed.txt"), "seed\n");
  G(repo, "add -A");
  G(repo, "commit -q -m seed");
  G(repo, `branch ${SHARED}`);
  return repo;
}

/** A worktree on a new ticket branch cut from the shared tip. */
function ticketWorktree(repo: string, branch: string): string {
  const root = mkdtempSync(path.join(tmpdir(), "to-done-wt-"));
  trash.push(root);
  const wt = path.join(root, "w");
  G(repo, `worktree add -q ${wt} -b ${branch} ${SHARED}`);
  return wt;
}

function commitInWorktree(wt: string, file: string, content: string): string {
  writeFileSync(path.join(wt, file), content);
  G(wt, "add -A");
  G(wt, `commit -q -m "work ${file}"`);
  return G(wt, "rev-parse HEAD");
}

/** A parked slot at a real commit, for the tests that seed prior slots. */
function seedSlot(repo: string, slot: string, file: string): string {
  const wt = ticketWorktree(repo, `tmp-${slot.replaceAll("/", "_")}`);
  const sha = commitInWorktree(wt, file, `${file}\n`);
  G(repo, `update-ref refs/heads/${slot} ${sha}`);
  G(repo, `worktree remove --force ${wt}`);
  G(repo, `update-ref -d refs/heads/tmp-${slot.replaceAll("/", "_")}`);
  return sha;
}

test.afterEach(() => process.chdir(cwd0));
test.after(() => {
  for (const dir of trash) {
    try {
      chmodSync(path.join(dir, ".git", "objects"), 0o755);
    } catch {
      /* not every trash dir is a repo */
    }
    rmSync(dir, { recursive: true, force: true });
  }
});

// Case 1: a work-carrying attempt parks at slot 1, and the ticket branch is gone.
test("work parks at slot 1", () => {
  const repo = makeRepo();
  const branch = `${SHARED}-7`;
  const wt = ticketWorktree(repo, branch);
  const tip = commitInWorktree(wt, "feature.txt", "done\n");
  process.chdir(repo);

  saveBailOut(ctx("github"), branch, 7, save());

  assert.ok(branchExists(`${SHARED}-wip-7-1`), "slot 1 exists");
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-1`), tip, "slot 1 holds the attempt's tip");
  assert.equal(branchExists(branch), false, "ticket branch is gone");
});

// Case 2: a dirty worktree is snapshotted, then parked, with the save message.
test("dirty worktree is snapshotted then parked", () => {
  const repo = makeRepo();
  const branch = `${SHARED}-7`;
  const wt = ticketWorktree(repo, branch);
  writeFileSync(path.join(wt, "wip.txt"), "half-done\n");
  process.chdir(repo);

  const s = save({ reason: "verification kept failing", attempt: 2, tries: 3 });
  saveBailOut(ctx("github"), branch, 7, s);

  assert.ok(branchExists(`${SHARED}-wip-7-1`), "slot 1 exists");
  assert.equal(
    G(repo, `show ${SHARED}-wip-7-1:wip.txt`),
    "half-done",
    "slot 1 carries the uncommitted change",
  );
  assert.equal(
    G(repo, `log -1 --format=%B ${SHARED}-wip-7-1`).trim(),
    bailOutMessage(ctx("github"), 7, s).trim(),
    "the snapshot uses bailOutMessage",
  );
  assert.equal(branchExists(branch), false, "ticket branch is gone");
});

// Case 3 (regression #338): a later empty attempt does not bury a slot.
test("a later empty attempt does not bury slot 1", () => {
  const repo = makeRepo();
  const branch = `${SHARED}-7`;
  const first = commitInWorktree(ticketWorktree(repo, branch), "feature.txt", "done\n");
  process.chdir(repo);
  saveBailOut(ctx("github"), branch, 7, save());
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-1`), first);

  // A fresh attempt that dies clean at the shared tip.
  ticketWorktree(repo, branch);
  saveBailOut(ctx("github"), branch, 7, save({ attempt: 2 }));

  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-1`), first, "slot 1 is untouched");
  assert.equal(branchExists(`${SHARED}-wip-7-2`), false, "no second slot for an empty attempt");
  assert.equal(branchExists(branch), false, "the empty ticket branch is dropped");
});

// Case 4: two attempts with work land in slots 1 and 2, both intact.
test("two attempts land in slots 1 and 2", () => {
  const repo = makeRepo();
  const branch = `${SHARED}-7`;

  const one = commitInWorktree(ticketWorktree(repo, branch), "a.txt", "one\n");
  process.chdir(repo);
  saveBailOut(ctx("github"), branch, 7, save({ attempt: 1 }));

  const two = commitInWorktree(ticketWorktree(repo, branch), "b.txt", "two\n");
  saveBailOut(ctx("github"), branch, 7, save({ attempt: 2 }));

  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-1`), one, "slot 1 intact");
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-2`), two, "slot 2 holds the second attempt");
});

// Case 5: a later park after slots 1 and 2 exist lands in slot 3.
test("a park after slots 1 and 2 lands in slot 3", () => {
  const repo = makeRepo();
  const branch = `${SHARED}-7`;
  const one = seedSlot(repo, `${SHARED}-wip-7-1`, "a.txt");
  const two = seedSlot(repo, `${SHARED}-wip-7-2`, "b.txt");

  const three = commitInWorktree(ticketWorktree(repo, branch), "c.txt", "three\n");
  process.chdir(repo);
  saveBailOut(ctx("github"), branch, 7, save({ attempt: 3 }));

  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-3`), three, "slot 3 holds the new work");
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-1`), one, "slot 1 unchanged");
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-2`), two, "slot 2 unchanged");
});

// Case 6: each open ticket's highest slot is picked, closed tickets skipped.
// (Case 7, classify(), is in failures.test.mts.)
test("stuckTickets picks the highest open slot and skips closed", () => {
  const repo = makeRepo();
  seedSlot(repo, `${SHARED}-wip-7-1`, "a.txt");
  const seven2 = seedSlot(repo, `${SHARED}-wip-7-2`, "b.txt");
  seedSlot(repo, `${SHARED}-wip-12-1`, "c.txt");
  process.chdir(repo);

  const stuck = stuckTickets(SHARED, (t) => t === 12);

  assert.deepEqual(stuck, [
    { ticket: 7, slot: `${SHARED}-wip-7-2`, remote: `${SHARED}-wip-7` },
  ]);
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-2`), seven2, "the selected slot is the highest");
});

// Case 6 (continued): the composer gets the unnumbered remote names, not slots.
test("publishStuckBranches publishes one unnumbered remote per open ticket", () => {
  const repo = makeRepo();
  const origin = mkdtempSync(path.join(tmpdir(), "to-done-origin-"));
  trash.push(origin);
  G(origin, "init -q --bare");
  G(repo, `remote add origin ${origin}`);
  seedSlot(repo, `${SHARED}-wip-7-1`, "a.txt");
  const seven2 = seedSlot(repo, `${SHARED}-wip-7-2`, "b.txt");
  seedSlot(repo, `${SHARED}-wip-12-1`, "c.txt");
  process.chdir(repo);

  const published = publishStuckBranches(SHARED, (t) => t === 12);

  assert.deepEqual(published, [`${SHARED}-wip-7`], "returns the unnumbered remote, ticket 12 skipped");
  assert.equal(G(origin, `rev-parse ${SHARED}-wip-7`), seven2, "origin holds the highest slot's commit");
  assert.throws(() => G(origin, `rev-parse ${SHARED}-wip-7-2`), "the numbered slot is not pushed");
  assert.throws(() => G(origin, `rev-parse ${SHARED}-wip-12`), "the closed ticket is not pushed");
});

// Case 8: a failed snapshot preserves the work rather than discarding it.
test(
  "a failed snapshot preserves the work",
  { skip: process.getuid?.() === 0 ? "read-only object store needs non-root" : false },
  () => {
    const repo = makeRepo();
    const branch = `${SHARED}-7`;
    const wt = ticketWorktree(repo, branch);
    writeFileSync(path.join(wt, "wip.txt"), "half-done\n");
    chmodSync(path.join(repo, ".git", "objects"), 0o555); // commit can no longer write
    process.chdir(repo);

    try {
      assert.throws(() => saveBailOut(ctx("github"), branch, 7, save()), /left intact for recovery/);
      assert.ok(branchExists(branch), "ticket branch is left in place");
      assert.ok(worktreeFor(branch), "worktree is not removed");
      assert.equal(branchExists(`${SHARED}-wip-7-1`), false, "no slot was created");
    } finally {
      chmodSync(path.join(repo, ".git", "objects"), 0o755);
    }
  },
);

// A failed slot write keeps the work on the ticket branch rather than losing it.
test("a failed slot write leaves the work on the ticket branch", () => {
  const repo = makeRepo();
  const branch = `${SHARED}-7`;
  const tip = commitInWorktree(ticketWorktree(repo, branch), "feature.txt", "done\n");
  // A nested ref makes `-wip-7-1` a directory, so writing that slot fails.
  G(repo, `update-ref refs/heads/${SHARED}-wip-7-1/x ${tip}`);
  process.chdir(repo);

  assert.throws(() => saveBailOut(ctx("github"), branch, 7, save()), /for recovery/);
  assert.equal(G(repo, `rev-parse ${branch}`), tip, "the ticket branch still holds the work");
  assert.equal(branchExists(`${SHARED}-wip-7-1`), false, "no slot was created");
});

// A failed push throws instead of dropping the ticket from the PR's list.
test("publishStuckBranches throws when a push fails", () => {
  const repo = makeRepo();
  G(repo, `remote add origin ${path.join(repo, "no-such-origin")}`);
  const slot = seedSlot(repo, `${SHARED}-wip-7-1`, "a.txt");
  process.chdir(repo);

  assert.throws(() => publishStuckBranches(SHARED, () => false));
  assert.equal(G(repo, `rev-parse ${SHARED}-wip-7-1`), slot, "the local slot is untouched");
});

// bailOutMessage content, against literals read from the plan, not the code.
test("bailOutMessage: github form", () => {
  assert.equal(
    bailOutMessage(ctx("github"), 338, { reason: "boom", attempt: 2, tries: 3 }),
    [
      "Save unfinished work for #338",
      "",
      "Attempt 2 of 3 did not close the ticket: boom",
      "The to-done loop saved the attempt's uncommitted changes here.",
      "Do not merge this commit as-is, take what is useful after inspection.",
      "",
      "_Generated by an AI agent._",
    ].join("\n"),
  );
});

test("bailOutMessage: local form names the ticket file", () => {
  assert.equal(
    bailOutMessage(ctx("local"), 7, {
      reason: "boom",
      attempt: 1,
      tries: 1,
      ticketFile: ".scratch/spec/issues/07-thing.md",
    }),
    [
      "Save unfinished work for ticket 07",
      "",
      "Ticket: .scratch/spec/issues/07-thing.md",
      "Attempt 1 of 1 did not close the ticket: boom",
      "The to-done loop saved the attempt's uncommitted changes here.",
      "Do not merge this commit as-is, take what is useful after inspection.",
      "",
      "_Generated by an AI agent._",
    ].join("\n"),
  );
});
